# Generated by Django 6.0.5 on 2026-05-19 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_remove_fixture_referee_fixture_away_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('Center Referee', 'Center Referee'), ('Assistant Referee', 'Assistant Referee'), ('Fourth Official', 'Fourth Official')], max_length=30)),
                ('experience_years', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='fixture',
            name='assistant_referee_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_one_matches', to='matches.referee'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='assistant_referee_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_two_matches', to='matches.referee'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='center_referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='center_matches', to='matches.referee'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='fourth_official',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fourth_matches', to='matches.referee'),
        ),
    ]
