# Generated by Django 6.0.5 on 2026-05-19 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_referee_fixture_assistant_referee_one_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='fourth_official',
        ),
        migrations.AddField(
            model_name='fixture',
            name='match_commissioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissioner_matches', to='matches.referee'),
        ),
        migrations.AlterField(
            model_name='referee',
            name='role',
            field=models.CharField(choices=[('Center Referee', 'Center Referee'), ('Assistant Referee', 'Assistant Referee'), ('Match Commissioner', 'Match Commissioner')], max_length=30),
        ),
    ]
