# Generated by Django 6.0.5 on 2026-05-20 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_remove_fixture_fourth_official_and_more'),
        ('teams', '0002_remove_team_coach_name_team_coach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='assistant_referee_one',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='assistant_referee_two',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='away_team',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='center_referee',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='home_team',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='match_commissioner',
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField()),
                ('home_score', models.IntegerField(default=0)),
                ('away_score', models.IntegerField(default=0)),
                ('played', models.BooleanField(default=False)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='teams.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='teams.team')),
            ],
        ),
    ]
