# Generated by Django 6.0.5 on 2026-05-20 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineups', '0005_alter_teamsheet_fixture'),
        ('matches', '0005_remove_fixture_assistant_referee_one_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fixture',
        ),
        migrations.DeleteModel(
            name='Referee',
        ),
    ]
