# Generated by Django 6.0.5 on 2026-05-20 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_match_venue_alter_match_away_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Center Referee', 'Center Referee'), ('Assistant Referee', 'Assistant Referee'), ('Match Commissioner', 'Match Commissioner')], max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='assistant_referee_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_referee_one', to='matches.referee'),
        ),
        migrations.AddField(
            model_name='match',
            name='assistant_referee_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_referee_two', to='matches.referee'),
        ),
        migrations.AddField(
            model_name='match',
            name='center_referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='center_referee', to='matches.referee'),
        ),
        migrations.AddField(
            model_name='match',
            name='match_commissioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_commissioner', to='matches.referee'),
        ),
    ]
