# Generated by Django 6.0.5 on 2026-05-20 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_referee_match_assistant_referee_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='fourth_official',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fourth_official', to='matches.referee'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='referee',
            name='role',
            field=models.CharField(choices=[('Center Referee', 'Center Referee'), ('Assistant Referee', 'Assistant Referee'), ('Fourth Official', 'Fourth Official'), ('Match Commissioner', 'Match Commissioner')], max_length=50),
        ),
        migrations.CreateModel(
            name='MatchReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('player_of_the_match', models.CharField(max_length=100)),
                ('referee_comments', models.TextField()),
                ('incidents', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
            ],
        ),
    ]
