# Generated by Django 6.0.5 on 2026-05-20 12:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_match_fourth_official_alter_match_match_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='center_referee',
        ),
        migrations.RemoveField(
            model_name='match',
            name='assistant_referee_two',
        ),
        migrations.RemoveField(
            model_name='match',
            name='fourth_official',
        ),
        migrations.RemoveField(
            model_name='match',
            name='match_commissioner',
        ),
        migrations.RemoveField(
            model_name='match',
            name='assistant_referee_one',
        ),
        migrations.RemoveField(
            model_name='match',
            name='played',
        ),
        migrations.RemoveField(
            model_name='matchreport',
            name='player_of_the_match',
        ),
        migrations.RemoveField(
            model_name='matchreport',
            name='summary',
        ),
        migrations.AddField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Played', 'Played')], default='Pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='Referee',
        ),
    ]
