# Generated by Django 6.0.5 on 2026-06-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0014_cleansheet_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchreport',
            name='assist_providers',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='matchreport',
            name='clean_shett_keepers',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='matchreport',
            name='goal_scorers',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='matchreport',
            name='red_card_players',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='matchreport',
            name='yellow_card_players',
            field=models.TextField(blank=True),
        ),
    ]
