# Generated by Django 6.0.5 on 2026-06-18 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0015_matchreport_assist_providers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchreport',
            old_name='clean_shett_keepers',
            new_name='clean_sheet_keepers',
        ),
    ]
