# Generated by Django 6.0.5 on 2026-06-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0016_rename_clean_shett_keepers_matchreport_clean_sheet_keepers'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchreport',
            name='away_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchreport',
            name='home_score',
            field=models.IntegerField(default=0),
        ),
    ]
