# Generated by Django 6.0.5 on 2026-05-20 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_remove_team_coach_contact_remove_team_coach_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='coach',
        ),
    ]
