# Generated by Django 6.0.5 on 2026-05-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_remove_team_coach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='team',
            name='reference_number',
        ),
        migrations.AddField(
            model_name='team',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
