# Generated by Django 6.0.5 on 2026-05-21 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_remove_team_logo_remove_team_reference_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='team',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='team',
            name='registration_fee_paid',
        ),
        migrations.CreateModel(
            name='TeamPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.IntegerField()),
                ('mpesa_code', models.CharField(max_length=20, unique=True)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
        ),
    ]
