# Generated by Django 6.0.5 on 2026-06-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_refereeprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='teampayment',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
    ]
