# Generated by Django 6.0.5 on 2026-06-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_alter_team_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='category',
            field=models.CharField(choices=[('Men', 'Men'), ('Ladies', 'Ladies')], default='Men', max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
