# Generated by Django 6.0.5 on 2026-08-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0012_team_category_team_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teampayment',
            name='payment_proof',
        ),
        migrations.AddField(
            model_name='teampayment',
            name='payment_message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='teampayment',
            name='payment_method',
            field=models.CharField(default='Simulated M-Pesa', max_length=30),
        ),
        migrations.AddField(
            model_name='teampayment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
