# Generated by Django 6.0.5 on 2026-08-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
    ]
