# Generated by Django 6.0.5 on 2026-05-21 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0007_remove_team_amount_paid_remove_team_payment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Team Registration', 'Team Registration'), ('Player Transfer', 'Player Transfer'), ('Fine', 'Fine'), ('Sponsorship', 'Sponsorship'), ('Match Revenue', 'Match Revenue'), ('Expense', 'Expense')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('transaction_date', models.DateField()),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.team')),
            ],
        ),
    ]
