# Generated by Django 6.0.5 on 2026-06-04 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_financerecord_coach_financerecord_payment_proof_and_more'),
        ('players', '0014_transferpayment_proof_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='financerecord',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.transfer'),
        ),
    ]
