# Generated by Django 6.0.5 on 2026-07-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_financerecord_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financerecord',
            name='category',
            field=models.CharField(choices=[('Team Registration', 'Team Registration'), ('Player Transfer', 'Player Transfer'), ('Individual Awards', 'Individual Awards'), ('Field Marking Lime', 'Field Marking Lime'), ('Referee Expenses (University)', 'Referee Expenses (University)'), ('Medical Expenses (University)', 'Medical Expenses (University)'), ('League Awards (University)', 'League Awards (University)')], max_length=100),
        ),
    ]
