# Generated by Django 6.0.5 on 2026-07-14 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_financerecord_category'),
        ('players', '0019_remove_transfer_reason_transfer_proof_of_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financerecord',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.player'),
        ),
    ]
