# Generated by Django 6.0.5 on 2026-07-14 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_financerecord_player'),
        ('teams', '0012_team_category_team_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='financerecord',
            name='referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.refereeprofile'),
        ),
    ]
