# Generated by Django 6.0.5 on 2026-08-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_financerecord_referee'),
    ]

    operations = [
        migrations.AddField(
            model_name='financerecord',
            name='payment_message',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='financerecord',
            name='payment_method',
            field=models.CharField(default='Simulated M-Pesa', max_length=30),
        ),
        migrations.AddField(
            model_name='financerecord',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='financerecord',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
