# Generated by Django 6.0.5 on 2026-05-19 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0002_remove_fixture_referee_fixture_away_score_and_more'),
        ('players', '0002_player_clean_sheets'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_name', models.CharField(max_length=100)),
                ('coach_contact', models.CharField(max_length=20)),
                ('assistant_coach_name', models.CharField(max_length=100)),
                ('assistant_coach_contact', models.CharField(max_length=20)),
                ('formation', models.CharField(max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_captain', to='players.player')),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.fixture')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='SubstitutePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jersey_number', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
                ('team_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lineups.teamsheet')),
            ],
        ),
        migrations.CreateModel(
            name='StartingPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('jersey_number', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
                ('team_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lineups.teamsheet')),
            ],
        ),
    ]
