# Generated by Django 6.0.5 on 2026-05-19 10:13

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substituteplayer',
            name='player',
        ),
        migrations.RemoveField(
            model_name='substituteplayer',
            name='team_sheet',
        ),
        migrations.RemoveField(
            model_name='teamsheet',
            name='captain',
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='player1',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='player10',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='player11',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='player2',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='player3',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='player4',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='player5',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='player6',
            field=models.CharField(default=datetime.datetime(2026, 5, 19, 10, 10, 26, 765950, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='player7',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='player8',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='player9',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='sub1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='sub10',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='sub2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='sub3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='sub4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='sub5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='sub6',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='sub7',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='sub8',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='sub9',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='StartingPlayer',
        ),
        migrations.DeleteModel(
            name='SubstitutePlayer',
        ),
    ]
