# Generated by Django 6.0.5 on 2026-05-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineups', '0002_remove_substituteplayer_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamsheet',
            name='captain_contact',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='captain_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
