# Generated by Django 6.0.5 on 2026-05-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineups', '0003_teamsheet_captain_contact_teamsheet_captain_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamsheet',
            old_name='sub1',
            new_name='player10_name',
        ),
        migrations.RenameField(
            model_name='teamsheet',
            old_name='sub10',
            new_name='player11_name',
        ),
        migrations.RenameField(
            model_name='teamsheet',
            old_name='sub2',
            new_name='player1_name',
        ),
        migrations.RenameField(
            model_name='teamsheet',
            old_name='sub3',
            new_name='player2_name',
        ),
        migrations.RenameField(
            model_name='teamsheet',
            old_name='sub4',
            new_name='player3_name',
        ),
        migrations.RenameField(
            model_name='teamsheet',
            old_name='sub5',
            new_name='player4_name',
        ),
        migrations.RenameField(
            model_name='teamsheet',
            old_name='sub6',
            new_name='player5_name',
        ),
        migrations.RenameField(
            model_name='teamsheet',
            old_name='sub7',
            new_name='player6_name',
        ),
        migrations.RenameField(
            model_name='teamsheet',
            old_name='sub8',
            new_name='player7_name',
        ),
        migrations.RenameField(
            model_name='teamsheet',
            old_name='sub9',
            new_name='player8_name',
        ),
        migrations.RemoveField(
            model_name='teamsheet',
            name='formation',
        ),
        migrations.RemoveField(
            model_name='teamsheet',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='teamsheet',
            name='player10',
        ),
        migrations.RemoveField(
            model_name='teamsheet',
            name='player11',
        ),
        migrations.RemoveField(
            model_name='teamsheet',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='teamsheet',
            name='player3',
        ),
        migrations.RemoveField(
            model_name='teamsheet',
            name='player4',
        ),
        migrations.RemoveField(
            model_name='teamsheet',
            name='player5',
        ),
        migrations.RemoveField(
            model_name='teamsheet',
            name='player6',
        ),
        migrations.RemoveField(
            model_name='teamsheet',
            name='player7',
        ),
        migrations.RemoveField(
            model_name='teamsheet',
            name='player8',
        ),
        migrations.RemoveField(
            model_name='teamsheet',
            name='player9',
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='player10_jersey',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='player10_position',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='player11_jersey',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='player11_position',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='player1_jersey',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='player1_position',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='player2_jersey',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='player2_position',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='player3_jersey',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='player3_position',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='player4_jersey',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='player4_position',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='player5_jersey',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='player5_position',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='player6_jersey',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='player6_position',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='player7_jersey',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='player7_position',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='player8_jersey',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='player8_position',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='player9_jersey',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='player9_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='player9_position',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='sub10_jersey',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='sub10_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='sub10_position',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='sub1_jersey',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='sub1_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='sub1_position',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='sub2_jersey',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='sub2_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='sub2_position',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='sub3_jersey',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='sub3_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='sub3_position',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='sub4_jersey',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='sub4_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='sub4_position',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='sub5_jersey',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='sub5_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='sub5_position',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='sub6_jersey',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='sub6_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='sub6_position',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='sub7_jersey',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='sub7_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='sub7_position',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='sub8_jersey',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='sub8_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='sub8_position',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='sub9_jersey',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='sub9_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teamsheet',
            name='sub9_position',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
