# Generated by Django 6.0.5 on 2026-05-20 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineups', '0004_rename_sub1_teamsheet_player10_name_and_more'),
        ('matches', '0005_remove_fixture_assistant_referee_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamsheet',
            name='fixture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match'),
        ),
    ]
