# Generated by Django 6.0.5 on 2026-05-20 06:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_clean_sheets'),
        ('teams', '0002_remove_team_coach_name_team_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='player',
            name='contract_period',
            field=models.CharField(choices=[('EOFL', 'End Of First Leg'), ('EOCS', 'End Of Current Season'), ('2S', 'Two Seasons')], default='EOCS', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='registration_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Transferred', 'Transferred'), ('Released', 'Released')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='student_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('from_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_team', to='teams.team')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
                ('to_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_team', to='teams.team')),
            ],
        ),
    ]
