# Generated by Django 6.0.5 on 2026-05-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_age_player_contract_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='age',
        ),
        migrations.RemoveField(
            model_name='player',
            name='contract_period',
        ),
        migrations.RemoveField(
            model_name='player',
            name='registration_date',
        ),
        migrations.RemoveField(
            model_name='player',
            name='status',
        ),
        migrations.RemoveField(
            model_name='player',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='approved',
        ),
        migrations.AddField(
            model_name='transfer',
            name='transfer_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
