# Generated by Django 6.0.5 on 2026-05-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_remove_player_age_remove_player_contract_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='approved_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
