# Generated by Django 6.0.5 on 2026-05-20 08:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_transfer_approved_by_admin_transfer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='approved_by_admin',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='transfer_fee',
        ),
        migrations.AddField(
            model_name='transfer',
            name='reason',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
