# Generated by Django 6.0.5 on 2026-05-20 10:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_remove_transfer_reason_player_age_player_suspended_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='created_at',
            new_name='date_given',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='suspended',
            new_name='is_suspended',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='full_name',
            new_name='player_name',
        ),
        migrations.RemoveField(
            model_name='card',
            name='minute',
        ),
        migrations.RemoveField(
            model_name='card',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='player',
            name='jersey_number',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='transfer_date',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='transfer_fee',
        ),
        migrations.AddField(
            model_name='transfer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='reason',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('Goalkeeper', 'Goalkeeper'), ('Defender', 'Defender'), ('Midfielder', 'Midfielder'), ('Forward', 'Forward')], max_length=50),
        ),
    ]
