# Generated by Django 6.0.5 on 2026-05-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_rename_created_at_card_date_given_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='jersey_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
