# Generated by Django 6.0.5 on 2026-05-21 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_player_jersey_number'),
        ('teams', '0006_remove_team_logo_remove_team_reference_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='assists',
        ),
        migrations.RemoveField(
            model_name='player',
            name='clean_sheets',
        ),
        migrations.RemoveField(
            model_name='player',
            name='red_cards',
        ),
        migrations.RemoveField(
            model_name='player',
            name='yellow_cards',
        ),
        migrations.AddField(
            model_name='player',
            name='school_id',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='player',
            name='jersey_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('Goalkeeper', 'Goalkeeper'), ('Defender', 'Defender'), ('Midfielder', 'Midfielder'), ('Forward', 'Forward')], default='Defender', max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='teams.team'),
        ),
    ]
