# Generated by Django 6.0.5 on 2026-05-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_remove_player_assists_remove_player_clean_sheets_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='date_given',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='card',
            name='minute_given',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='red_cards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='yellow_cards',
            field=models.IntegerField(default=0),
        ),
    ]
