# Generated by Django 6.0.5 on 2026-05-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_rename_date_given_card_created_at_card_minute_given_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='assists',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='clean_sheets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='goal_conceded',
            field=models.IntegerField(default=0),
        ),
    ]
