# Generated by Django 6.0.5 on 2026-06-04 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_player_assists_player_clean_sheets_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_code', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transfer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='players.transfer')),
            ],
        ),
    ]
