# Generated by Django 6.0.5 on 2026-06-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0013_transferpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferpayment',
            name='proof_of_payment',
            field=models.FileField(blank=True, null=True, upload_to='transfer_payments/'),
        ),
    ]
