# Generated by Django 6.0.5 on 2026-06-05 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0017_player_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
    ]
