# Generated by Django 6.0.5 on 2026-06-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0018_remove_player_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='reason',
        ),
        migrations.AddField(
            model_name='transfer',
            name='proof_of_payment',
            field=models.ImageField(blank=True, null=True, upload_to='transfer_proofs/'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='transaction_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
