# Generated by Django 6.0.5 on 2026-08-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0019_remove_transfer_reason_transfer_proof_of_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='transfer_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
