# Generated by Django 6.0.5 on 2026-08-04 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0020_transfer_transfer_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='proof_of_payment',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='transaction_code',
        ),
        migrations.RemoveField(
            model_name='transferpayment',
            name='proof_of_payment',
        ),
        migrations.RemoveField(
            model_name='transferpayment',
            name='transaction_code',
        ),
    ]
