# Generated by Django 6.0.5 on 2026-08-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0021_remove_transfer_proof_of_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferpayment',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
