# Generated by Django 6.0.5 on 2026-06-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='audience',
            field=models.CharField(choices=[('all', 'All Users'), ('coaches', 'Coaches Only'), ('referees', 'Referees Only')], default='all', max_length=20),
        ),
    ]
