# Generated by Django 6.0.5 on 2026-07-11 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0019_remove_transfer_reason_transfer_proof_of_payment_and_more'),
        ('teams', '0012_team_category_team_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=20)),
                ('award_name', models.CharField(choices=[('Golden Boot', 'Golden Boot'), ('Golden Glove', 'Golden Glove'), ('Top Playmaker', 'Top Playmaker'), ('League Champion', 'League Champion'), ('Runner Up', 'Runner Up'), ('Fair Play', 'Fair Play'), ('Player of the Season', 'Player of the Season'), ('Team of the Season', 'Team of the Season')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('date_awarded', models.DateField(auto_now_add=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.team')),
            ],
        ),
    ]
